### ISSUE TITLE
broken link for repository

### ISSUE THREAD

**Issue by loafyloaf** [WASdev/sample.microservicebuilder.helm.elk#2]
the helm chart repo listed on this page (https://wasdev.github.io/sample.microservicebuilder.helm.elk/charts) returns 404

**Comment by fmhwong** [comment]
There is nothing to see from this link on a browser.  It is used to host the repo.  If you'd like to see the source, go to https://github.com/WASdev/sample.microservicebuilder.helm.elk/tree/gh-pages/charts.
