### ISSUE TITLE
Typo in the directions - configure Liberty server step 1

### ISSUE THREAD

**Issue by kdurston** [WASdev/sample.microservicebuilder.helm.elk#3]
It says this: 

Ensure that the Kubernetes secrets exist. Run the following kubectl command and find the **mb-truststore, mb-truststore**, mb-keystore and mb-keystore-password Kubernetes secrets in the list:

Believe it should say:.

Ensure that the Kubernetes secrets exist. Run the following kubectl command and find the **mb-truststore, mb-truststore-password,** mb-keystore and mb-keystore-password Kubernetes secrets in the list:

**Comment by fmhwong** [comment]
Fixed in https://github.com/WASdev/sample.microservicebuilder.helm.elk/commit/1db4124e68f234e7a6314895b52fafbba16e1332

**Comment by fmhwong** [comment]
Thanks for reporting!  Fixed in https://github.com/WASdev/sample.microservicebuilder.helm.elk/commit/1db4124e68f234e7a6314895b52fafbba16e1332
