### ISSUE TITLE
chart url time out

### ISSUE THREAD

**Issue by wofish2** [WASdev/sample.microservicebuilder.helm.elk#4]
Cannot access the following chart URL :
https://wasdev.github.io/sample.microservicebuilder.helm.elk/charts

**Comment by fmhwong** [comment]
You cannot open https://wasdev.github.io/sample.microservicebuilder.helm.elk/charts from a browser.  Follow the instructions [here](https://github.com/WASdev/sample.microservicebuilder.helm.elk/blob/master/installing_sample_elk_task.md#install-the-microservice-builder-elk-sample-locally-on-a-minikube-environment) to install the chart.
